name: "Podcast Generator"
author: "Adam Boudreau"
description: "Generates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icons: "git-branch"
  color: "red"
inputs:
  email: 
    description: true
    default: ${{ github.actor }}@localhost
  name: 
    description: The committer's name
    required: true
    default: ${{ github.actor }}      